vich_uploader:
    db_driver: orm

    mappings:
        picture_file:
            uri_prefix: /uploads/project
            upload_destination: '%upload_directory%/project'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        user_file:
            uri_prefix: /uploads/user
            upload_destination: '%upload_directory%/user'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        techno_file:
            uri_prefix: /uploads/techno
            upload_destination: '%upload_directory%/techno'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        client_file:
            uri_prefix: /uploads/client
            upload_destination: '%upload_directory%/client'
            namer: Vich\UploaderBundle\Naming\UniqidNamer